# Generated by Django 6.0.6 on 2026-09-12 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Criado'), ('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('canceled', 'Cancelado'), ('expired', 'Expirado'), ('error', 'Erro de integração')], db_index=True, default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mercado_pago_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('mercado_pago_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('provider_status_detail', models.CharField(blank=True, max_length=100)),
                ('pix_copy_paste', models.TextField(blank=True)),
                ('ticket_url', models.URLField(blank=True, max_length=2048)),
                ('last_error', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['created', 'pending'])), fields=('order',), name='one_active_payment_per_order'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive')],
            },
        ),
    ]
