# Generated by Django 6.0.6 on 2026-10-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cancel_idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
