# Generated by Django 6.0.6 on 2026-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="selected",
            field=models.CharField(
                choices=[
                    ("selected", "Selecionado"),
                    ("no-selected", "Não Selecionado"),
                ],
                db_index=True,
                default="selected",
                max_length=20,
            ),
        ),
    ]
