# Generated by Django 6.0.6 on 2026-08-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="expires_at",
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("paid", "Pago"),
                    ("shipped", "Enviado"),
                    ("delivered", "Entregue"),
                    ("cancelled", "Cancelado"),
                    ("processing", "Processando"),
                    ("expired", "Expirado"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
