# Generated by Django 6.0.6 on 2026-08-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancelled_at_order_expires_at_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expired_at',
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
