# Generated by Django 6.0.6 on 2026-09-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
