# Generated by Django 6.0.6 on 2026-08-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("uses", models.PositiveIntegerField()),
                ("used", models.PositiveIntegerField()),
                (
                    "min_value_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("activated", models.BooleanField(default=True)),
                ("expires", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("uses__gt", 0)), name="cupom_uses_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("used__lte", models.F("uses"))),
                        name="coupon_used_lte_uses",
                    ),
                ],
            },
        ),
    ]
