# Generated by Django 6.0.6 on 2026-06-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome da Loja')),
                ('description', models.CharField(blank=True)),
                ('document', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Loja Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
